---
name: Run Fleet server and extract Elastic integration
'on':
  pull_request:
  push:

jobs:

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 8.15.1
        distro:
          - ubuntu-22.04

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Start containers
        run: |
          cd molecule/setup/es_kb_fleet
          sed -i 's/^STACK_VERSION=.*/STACK_VERSION=${{ matrix.version }}/g' .env
          ./elastic-container.sh start

      - name: Install scripts dependencies.
        run: pip3 install -r ./scripts/requirements.txt

      - name: Run scripts
        run: |
          python3 ./scripts/install_integration.py
          python3 ./scripts/dump_index_templates.py
          python3 ./scripts/dump_ingest.py
          python3 ./scripts/dump_kibana_objects.py

      - name: Stop containers
        if: always()
        run: |
          cd molecule/setup/es_kb_fleet
          STACK_VERSION=${{ matrix.version }} ./elastic-container.sh destroy
